import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, ArrowUpRight, Check, ChevronDown, Code2, Compass, Globe2, Layers3, Rocket, ShoppingCart, Sparkles } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { T, useLanguage } from "../context/LanguageContext";

const services = [
  { number: "01", title: "Landing Pages", label: { es: "CONVERSIÓN", en: "CONVERSION" }, description: { es: "Páginas claras y veloces para que las personas correctas entiendan el valor y den el siguiente paso.", en: "Clear, fast pages that help the right people understand your value and take the next step." }, points: [{ es: "Captura rápida de leads", en: "Fast lead capture" }, { es: "Diseño móvil optimizado", en: "Mobile-first layout" }, { es: "WhatsApp directo integrado", en: "Direct WhatsApp integration" }], href: "/blog/landing-pages-conversion", icon: Layers3 },
  { number: "02", title: "E-commerce", label: { es: "VENTAS 24/7", en: "SELL 24/7" }, description: { es: "Plataformas de venta online diseñadas para que el recorrido de compra sea ágil, seguro y fácil de administrar.", en: "Online sales platforms designed to keep the buying journey effortless, secure and easy to manage." }, points: [{ es: "Pasarela segura de pago", en: "Secure payment gateway" }, { es: "Administrador de productos", en: "Product management" }, { es: "Compra ágil", en: "Frictionless checkout" }], href: "/blog/ecommerce-alto-nivel", icon: ShoppingCart },
  { number: "03", title: { es: "Webs Corporativas", en: "Corporate Websites" }, label: { es: "AUTORIDAD", en: "AUTHORITY" }, description: { es: "Una identidad digital sólida para empresas que necesitan transmitir confianza, criterio y dirección.", en: "A solid digital identity for companies that need to communicate trust, judgment and direction." }, points: [{ es: "Arquitectura a medida", en: "Custom architecture" }, { es: "Estrategia de contenido", en: "Content strategy" }, { es: "Escalable desde el inicio", en: "Scalable from day one" }], href: "/blog/webs-corporativas-identidad", icon: Globe2 },
];

const plans = [
  { number: "01", title: { es: "Paquete Destello", en: "Flash Package" }, price: "$299", description: { es: "Una página diseñada para convertir visitantes en clientes desde el primer scroll.", en: "One page designed to turn visitors into clients from the first scroll." }, items: [{ es: "Diseño exclusivo y responsivo", en: "Exclusive responsive design" }, { es: "WhatsApp integrado", en: "WhatsApp integration" }, { es: "SEO On-Page", en: "On-page SEO" }, { es: "Entrega en 1–2 semanas", en: "Delivered in 1–2 weeks" }], warranty: { es: "30 días de garantía post-lanzamiento", en: "30-day post-launch warranty" } },
  { number: "02", title: { es: "Paquete Constelación", en: "Constellation Package" }, price: "$699", description: { es: "Sitio corporativo de hasta 5 páginas con chatbot IA, blog y Analytics.", en: "Corporate site of up to 5 pages with an AI chatbot, blog and Analytics." }, items: [{ es: "Todo lo de Destello", en: "Everything in Flash" }, { es: "Hasta 5 páginas", en: "Up to 5 pages" }, { es: "Chatbot IA 24/7", en: "24/7 AI chatbot" }, { es: "SEO Técnico + Search Console", en: "Technical SEO + Search Console" }], warranty: { es: "60 días de garantía post-lanzamiento", en: "60-day post-launch warranty" }, featured: true },
  { number: "03", title: { es: "Paquete Nova", en: "Nova Package" }, price: "$1,299", description: { es: "Plataforma de ventas completa con pagos, panel administrativo y una herramienta IA.", en: "Complete sales platform with payments, an admin panel and one AI tool." }, items: [{ es: "Todo lo de Constelación", en: "Everything in Constellation" }, { es: "E-commerce + Stripe y PayPal", en: "E-commerce + Stripe and PayPal" }, { es: "Panel admin personalizado", en: "Custom admin panel" }, { es: "Schema Markup", en: "Schema Markup" }], warranty: { es: "90 días de garantía prioritaria", en: "90-day priority warranty" } },
];

const faqs = [
  { es: "¿Cuánto cuesta un proyecto?", en: "How much does a project cost?", answerEs: "Los proyectos profesionales y personalizados comienzan desde $299 USD. La inversión se define con claridad según la complejidad y las necesidades del negocio.", answerEn: "Custom professional projects start at $299 USD. The investment is defined clearly around the business's complexity and needs." },
  { es: "¿Ofrecen facilidades de pago?", en: "Do you offer payment plans?", answerEs: "Sí. Trabajamos con 50% al iniciar el proyecto y 50% al momento del lanzamiento. En proyectos mayores podemos estructurar pagos por fases.", answerEn: "Yes. We work with 50% to start and 50% at launch. For larger projects, we can structure milestone payments." },
  { es: "¿Cuánto tiempo toma un proyecto?", en: "How long does a project take?", answerEs: "Depende de la complejidad. Una landing page suele estar lista en 2 semanas y una web corporativa completa puede tomar entre 4 y 6 semanas.", answerEn: "It depends on complexity. A landing page is usually ready in 2 weeks, while a complete corporate website can take 4 to 6 weeks." },
  { es: "¿Trabajan con SEO y mantenimiento?", en: "Do you provide SEO and maintenance?", answerEs: "Sí. Todas nuestras webs nacen con una estructura SEO On-Page optimizada y contamos con planes de soporte para mantenerlas actualizadas y seguras.", answerEn: "Yes. Every website starts with optimized on-page SEO and we offer support plans to keep it current and secure." },
];

function ProjectFrame({ className = "" }: { className?: string }) {
  return <figure className={`mercury-card overflow-hidden ${className}`}><div className="flex h-10 items-center gap-2 border-b border-white/10 px-4" aria-hidden="true"><span className="h-2 w-2 rounded-full bg-[#70707d]" /><span className="h-2 w-2 rounded-full bg-[#70707d]" /><span className="h-2 w-2 rounded-full bg-[#70707d]" /><span className="ml-4 h-4 max-w-72 flex-1 rounded-full bg-white/[0.08]" /></div><div className="relative aspect-video overflow-hidden"><img src="/screenshots/la-reja-desktop.svg" alt="Vista de La Reja, proyecto del portafolio de Polaris Web Studio" className="h-full w-full object-cover object-top" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#171721]/90 via-[#171721]/30 to-transparent px-5 pb-5 pt-16"><p className="text-sm text-[#ededf3]">La Reja · <T en="Digital restaurant experience">Experiencia gastronómica digital</T></p></div></div></figure>;
}

function SectionEyebrow({ children }: { children: React.ReactNode }) {
  return <p className="text-xs font-medium tracking-[0.01em] text-[#c3c3cc]">{children}</p>;
}

export default function LandingPage() {
  const navigate = useNavigate();
  const { language } = useLanguage();
  const reducedMotion = useReducedMotion();
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  useEffect(() => {
    document.title = language === "es" ? "Polaris Web Studio | Diseño y Desarrollo de Páginas Web Premium" : "Polaris Web Studio | Premium Web Design & Development";
    const meta = document.querySelector('meta[name="description"]') ?? document.head.appendChild(document.createElement("meta"));
    meta.setAttribute("name", "description");
    meta.setAttribute("content", language === "es" ? "Diseñamos y desarrollamos experiencias web originales para atraer clientes y hacer crecer negocios." : "We design and develop original web experiences that attract clients and help businesses grow.");
  }, [language]);

  const reveal = (delay = 0) => ({ initial: { opacity: 0, y: reducedMotion ? 0 : 14 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.16 }, transition: { duration: reducedMotion ? 0 : 0.46, delay, ease: [0.16, 1, 0.3, 1] as [number, number, number, number] } });

  return <div className="mercury-page min-h-screen overflow-x-clip bg-[#171721] text-[#ededf3]"><Navbar variant="mercury" /><main>
    <section className="relative isolate flex min-h-[100svh] items-center overflow-hidden bg-[#171721] px-6 pb-20 pt-28 md:px-12 lg:px-16">
      <img src="/screenshots/la-reja-desktop.svg" alt="" className="absolute inset-0 -z-20 h-full w-full object-cover opacity-35 grayscale" aria-hidden="true" />
      <div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(23,23,33,.96)_0%,rgba(23,23,33,.86)_38%,rgba(23,23,33,.72)_100%)]" aria-hidden="true" />
      <div className="absolute inset-0 -z-10 bg-[linear-gradient(0deg,rgba(23,23,33,1)_0%,transparent_42%,rgba(23,23,33,.35)_100%)]" aria-hidden="true" />
      <motion.div initial={{ opacity: 0, y: reducedMotion ? 0 : 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reducedMotion ? 0 : 0.56, ease: [0.16, 1, 0.3, 1] as [number, number, number, number] }} className="mx-auto w-full max-w-[760px] text-center">
        <p className="text-xs font-medium tracking-[0.01em] text-[#c3c3cc]"><T en="POLARIS WEB STUDIO · DIGITAL EXPERIENCES WITH INTENTION">POLARIS WEB STUDIO · EXPERIENCIAS DIGITALES CON INTENCIÓN</T></p>
        <h1 className="mercury-display mt-7 text-5xl leading-[1.08] text-[#ededf3] sm:text-6xl md:text-7xl"><T en="We digitize the future of your business today.">Digitalizamos el futuro de tu negocio hoy.</T></h1>
        <p className="mx-auto mt-7 max-w-xl text-base leading-relaxed text-[#c3c3cc] sm:text-lg"><T en="Websites and digital tools designed to help people discover your business, understand it and take the next step.">Sitios web y herramientas digitales diseñados para que las personas descubran tu negocio, lo entiendan y den el siguiente paso.</T></p>
        <div className="mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row"><button type="button" onClick={() => navigate("/cotizar")} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#5266eb] px-6 py-3 text-base font-medium text-white transition-colors hover:bg-[#6275ff] active:scale-[0.98] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#5266eb]/35"><T en="Plan your project">Planifica tu proyecto</T><ArrowRight size={18} aria-hidden="true" /></button><a href="#estudio" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-[#ededf3] px-6 py-3 text-base font-medium text-[#ededf3] transition-colors hover:bg-white/10 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/20"><T en="Discover Polaris">Conoce Polaris</T><ArrowUpRight size={18} aria-hidden="true" /></a></div>
      </motion.div>
      <p className="absolute bottom-7 left-6 text-xs text-[#c3c3cc] md:left-12 lg:left-16"><T en="Featured work · La Reja">Proyecto destacado · La Reja</T></p>
    </section>

    <section id="estudio" className="bg-[#171721] px-6 py-[72px] md:px-12 lg:px-16"><motion.div {...reveal()} className="mx-auto grid max-w-[1200px] gap-10 border-y border-white/10 py-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><SectionEyebrow><T en="A SMALL STUDIO WITH A CLEAR POINT OF VIEW">UN ESTUDIO PEQUEÑO CON UNA MIRADA CLARA</T></SectionEyebrow><h2 className="mercury-display mt-5 max-w-md text-3xl leading-[1.15] text-[#ededf3] sm:text-4xl"><T en="What your business says online should feel considered.">Lo que tu negocio comunica online debe sentirse pensado.</T></h2></div><p className="max-w-2xl text-base leading-relaxed text-[#c3c3cc]"><T en="We pair strategy, original code and a disciplined design process to make digital experiences that feel aligned with the business behind them.">Unimos estrategia, código original y un proceso de diseño disciplinado para crear experiencias digitales alineadas con el negocio que las respalda.</T></p></motion.div></section>

    <section id="servicios" className="bg-[#171721] px-6 py-[72px] md:px-12 lg:px-16"><div className="mx-auto max-w-[1200px]"><motion.header {...reveal()} className="max-w-xl"><SectionEyebrow><T en="WHAT WE BUILD">LO QUE CONSTRUIMOS</T></SectionEyebrow><h2 className="mercury-display mt-5 text-3xl leading-[1.15] text-[#ededf3] sm:text-4xl"><T en="Digital foundations for the work ahead.">Bases digitales para el trabajo que viene.</T></h2></motion.header><div className="mt-12 grid gap-3 md:grid-cols-3">{services.map((service, index) => { const Icon = service.icon; const titleEs = typeof service.title === "string" ? service.title : service.title.es; const titleEn = typeof service.title === "string" ? service.title : service.title.en; return <motion.article {...reveal(index * 0.06)} key={service.number} className="mercury-card flex min-h-[360px] flex-col p-8"><div className="flex items-center justify-between"><span className="text-sm text-[#c3c3cc]">{service.number}</span><Icon size={20} className="text-[#ededf3]" aria-hidden="true" /></div><p className="mt-10 text-xs text-[#c3c3cc]"><T en={service.label.en}>{service.label.es}</T></p><h3 className="mercury-display mt-3 text-3xl leading-[1.15] text-[#ededf3]"><T en={titleEn}>{titleEs}</T></h3><p className="mt-4 text-sm leading-relaxed text-[#c3c3cc]"><T en={service.description.en}>{service.description.es}</T></p><ul className="mt-7 space-y-2.5">{service.points.map((point) => <li key={point.es} className="flex gap-2 text-sm text-[#c3c3cc]"><Check size={15} className="mt-0.5 shrink-0 text-[#ededf3]" aria-hidden="true" /><T en={point.en}>{point.es}</T></li>)}</ul><Link to={service.href} className="mt-auto pt-8 text-sm text-[#ededf3] underline decoration-[#70707d] underline-offset-4 hover:decoration-[#ededf3] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#5266eb]"><T en="Read more">Ver más</T></Link></motion.article>; })}</div></div></section>

    <section id="portafolio" className="bg-[#171721] px-6 py-[72px] md:px-12 lg:px-16"><div className="mx-auto grid max-w-[1200px] gap-10 lg:grid-cols-[0.85fr_1.15fr] lg:items-center"><motion.div {...reveal()}><SectionEyebrow><T en="SELECTED WORK">PROYECTOS SELECCIONADOS</T></SectionEyebrow><h2 className="mercury-display mt-5 max-w-md text-3xl leading-[1.15] text-[#ededf3] sm:text-4xl"><T en="The best work begins with an honest point of view.">El mejor trabajo comienza con un punto de vista honesto.</T></h2><p className="mt-6 max-w-md text-base leading-relaxed text-[#c3c3cc]"><T en="Every project begins with a different audience, business model and ambition. The outcome should never look borrowed.">Cada proyecto comienza con un público, modelo de negocio y ambición distintos. El resultado no debe parecer prestado.</T></p><Link to="/portafolio" className="mt-8 inline-flex min-h-11 items-center gap-2 rounded-full border border-[#ededf3] px-5 py-2 text-sm font-medium text-[#ededf3] hover:bg-white/10 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#5266eb]/35"><T en="See the portfolio">Ver el portafolio</T><ArrowRight size={16} aria-hidden="true" /></Link></motion.div><motion.div {...reveal(0.08)}><ProjectFrame /></motion.div></div></section>

    <section id="proceso" className="bg-[#171721] px-6 py-[72px] md:px-12 lg:px-16"><div className="mx-auto max-w-[1200px]"><motion.header {...reveal()} className="max-w-xl"><SectionEyebrow><T en="A WAY OF WORKING">UNA FORMA DE TRABAJAR</T></SectionEyebrow><h2 className="mercury-display mt-5 text-3xl leading-[1.15] text-[#ededf3] sm:text-4xl"><T en="A clear path keeps the work moving.">Un camino claro mantiene el trabajo en movimiento.</T></h2></motion.header><div className="mt-12 grid gap-3 md:grid-cols-3">{[{ n: "01", es: "Planificamos", en: "We plan", copyEs: "Alineamos objetivos, público, alcance y las decisiones que realmente importan.", copyEn: "We align goals, audience, scope and the decisions that really matter." }, { n: "02", es: "Diseñamos", en: "We design", copyEs: "Convertimos la estrategia en una experiencia clara, distintiva y preparada para convertir.", copyEn: "We turn strategy into a clear, distinctive experience ready to convert." }, { n: "03", es: "Lanzamos", en: "We launch", copyEs: "Publicamos sobre una base técnica sólida y acompañamos los primeros pasos.", copyEn: "We launch on a solid technical foundation and support the first steps." }].map((step, index) => <motion.article {...reveal(index * 0.06)} key={step.n} className="mercury-card p-8"><span className="text-sm text-[#c3c3cc]">{step.n}</span><h3 className="mercury-display mt-11 text-3xl leading-[1.15] text-[#ededf3]"><T en={step.en}>{step.es}</T></h3><p className="mt-4 text-sm leading-relaxed text-[#c3c3cc]"><T en={step.copyEn}>{step.copyEs}</T></p></motion.article>)}</div><Link to="/proceso" className="mt-8 inline-flex text-sm text-[#ededf3] underline decoration-[#70707d] underline-offset-4 hover:decoration-[#ededf3] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#5266eb]"><T en="Explore the process">Conoce la metodología</T></Link></div></section>

    <section id="precios" className="bg-[#171721] px-6 py-[72px] md:px-12 lg:px-16"><div className="mx-auto max-w-[1200px]"><motion.header {...reveal()} className="max-w-xl"><SectionEyebrow><T en="TRANSPARENT PRICING">INVERSIÓN TRANSPARENTE</T></SectionEyebrow><h2 className="mercury-display mt-5 text-3xl leading-[1.15] text-[#ededf3] sm:text-4xl"><T en="A clear starting point for every stage.">Un punto de partida claro para cada etapa.</T></h2><p className="mt-5 text-base leading-relaxed text-[#c3c3cc]"><T en="Fixed prices, no hidden costs. Start with the scope that makes sense today.">Precios fijos, sin costos ocultos. Empieza con el alcance que tiene sentido hoy.</T></p></motion.header><div className="mt-12 grid gap-3 md:grid-cols-3">{plans.map((plan, index) => <motion.article {...reveal(index * 0.06)} key={plan.number} className="mercury-card relative flex min-h-[440px] flex-col p-8">{plan.featured && <span className="absolute right-5 top-5 rounded-full bg-[#272735] px-3 py-1 text-xs text-[#ededf3]"><T en="Most popular">Más popular</T></span>}<span className="text-sm text-[#c3c3cc]">{plan.number}</span><h3 className="mercury-display mt-10 text-3xl leading-[1.15] text-[#ededf3]"><T en={plan.title.en}>{plan.title.es}</T></h3><p className="mercury-display mt-6 text-4xl leading-none text-[#ededf3]">{plan.price}</p><p className="mt-5 text-sm leading-relaxed text-[#c3c3cc]"><T en={plan.description.en}>{plan.description.es}</T></p><ul className="mt-6 space-y-2.5">{plan.items.map((item) => <li key={item.es} className="flex gap-2 text-sm text-[#c3c3cc]"><Check size={15} className="mt-0.5 shrink-0 text-[#ededf3]" aria-hidden="true" /><T en={item.en}>{item.es}</T></li>)}</ul><p className="mt-auto pt-8 text-xs text-[#c3c3cc]"><T en={plan.warranty.en}>{plan.warranty.es}</T></p><button type="button" onClick={() => navigate("/cotizar")} className="mt-5 inline-flex min-h-11 items-center justify-center rounded-full border border-[#ededf3] px-5 py-2 text-sm font-medium text-[#ededf3] hover:bg-white/10 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#5266eb]/35"><T en="Start here">Comenzar</T></button></motion.article>)}</div><p className="mt-7 text-xs text-[#c3c3cc]"><T en="All packages include a domain up to $15 USD (first year), SSL and managed hosting.">Todos los paquetes incluyen dominio web hasta $15 USD (primer año), SSL y hosting administrado.</T></p></div></section>

    <section id="soluciones" className="bg-[#171721] px-6 py-[72px] md:px-12 lg:px-16"><div className="mx-auto max-w-[1200px]"><motion.header {...reveal()} className="max-w-xl"><SectionEyebrow><T en="THE POLARIS ECOSYSTEM">EL ECOSISTEMA POLARIS</T></SectionEyebrow><h2 className="mercury-display mt-5 text-3xl leading-[1.15] text-[#ededf3] sm:text-4xl"><T en="More ways to move a business forward.">Más formas de impulsar un negocio.</T></h2></motion.header><div className="mt-12 grid gap-3 md:grid-cols-3">{[{ label: { es: "NÚCLEO DIGITAL", en: "DIGITAL CORE" }, title: { es: "Diseño y desarrollo web", en: "Web design and development" }, text: { es: "Landing pages, webs corporativas y e-commerce construidos alrededor de objetivos reales.", en: "Landing pages, corporate websites and e-commerce built around real goals." }, link: "/cotizar", action: { es: "Cotiza tu proyecto", en: "Quote your project" }, icon: Code2 }, { label: { es: "PRESENCIA LOCAL", en: "LOCAL PRESENCE" }, title: { es: "Local Lift", en: "Local Lift" }, text: { es: "Una forma enfocada de mejorar cómo aparece, comunica y se descubre un negocio a nivel local.", en: "A focused way to improve how a business appears, communicates and gets discovered locally." }, link: "/local-lift", action: { es: "Conoce Local Lift", en: "Explore Local Lift" }, icon: Compass }, { label: { es: "OPERACIONES", en: "OPERATIONS" }, title: { es: "Polaris Flow", en: "Polaris Flow" }, text: { es: "Sistemas enfocados para ordenar las partes repetitivas del negocio y avanzar con más claridad.", en: "Focused systems that organize a business's repetitive parts and help the team move with more clarity." }, link: "/flow", action: { es: "Explora Polaris Flow", en: "Explore Polaris Flow" }, icon: Sparkles }].map((solution, index) => { const Icon = solution.icon; return <motion.article {...reveal(index * 0.06)} key={solution.title.en} className="mercury-card flex min-h-[280px] flex-col p-8"><Icon size={20} className="text-[#ededf3]" aria-hidden="true" /><p className="mt-9 text-xs text-[#c3c3cc]"><T en={solution.label.en}>{solution.label.es}</T></p><h3 className="mercury-display mt-3 text-3xl leading-[1.15] text-[#ededf3]"><T en={solution.title.en}>{solution.title.es}</T></h3><p className="mt-4 text-sm leading-relaxed text-[#c3c3cc]"><T en={solution.text.en}>{solution.text.es}</T></p><Link to={solution.link} className="mt-auto pt-7 text-sm text-[#ededf3] underline decoration-[#70707d] underline-offset-4 hover:decoration-[#ededf3] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#5266eb]"><T en={solution.action.en}>{solution.action.es}</T></Link></motion.article>; })}</div></div></section>

    <section id="faq" className="bg-[#171721] px-6 py-[72px] md:px-12 lg:px-16"><div className="mx-auto grid max-w-[1200px] gap-12 border-t border-white/10 pt-16 lg:grid-cols-[0.75fr_1.25fr]"><motion.header {...reveal()}><SectionEyebrow><T en="COMMON QUESTIONS">DUDAS COMUNES</T></SectionEyebrow><h2 className="mercury-display mt-5 max-w-md text-3xl leading-[1.15] text-[#ededf3] sm:text-4xl"><T en="The details should be as clear as the idea.">Los detalles deben ser tan claros como la idea.</T></h2><Link to="/contacto" className="mt-7 inline-flex text-sm text-[#ededf3] underline decoration-[#70707d] underline-offset-4 hover:decoration-[#ededf3] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#5266eb]"><T en="Contact Polaris">Contactar a Polaris</T></Link></motion.header><div>{faqs.map((faq, index) => { const open = openFaq === index; return <motion.article {...reveal(index * 0.04)} key={faq.es} className="border-b border-white/10"><button type="button" onClick={() => setOpenFaq(open ? null : index)} aria-expanded={open} className="flex w-full items-center justify-between gap-6 py-6 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#5266eb]"><span className="mercury-display text-xl leading-[1.2] text-[#ededf3] sm:text-2xl"><T en={faq.en}>{faq.es}</T></span><ChevronDown size={20} className={`shrink-0 text-[#ededf3] transition-transform ${open ? "rotate-180" : ""}`} aria-hidden="true" /></button>{open && <p className="max-w-2xl pb-6 text-sm leading-relaxed text-[#c3c3cc]"><T en={faq.answerEn}>{faq.answerEs}</T></p>}</motion.article>; })}</div></div></section>

    <section className="bg-[#171721] px-6 py-[100px] md:px-12 lg:px-16"><motion.div {...reveal()} className="mercury-card mx-auto max-w-[1200px] px-7 py-16 text-center sm:px-12"><SectionEyebrow><T en="READY WHEN YOU ARE">CUANDO ESTÉS LISTO</T></SectionEyebrow><h2 className="mercury-display mx-auto mt-5 max-w-3xl text-3xl leading-[1.15] text-[#ededf3] sm:text-4xl"><T en="Build the next thing your business needs to be seen for.">Construyamos eso por lo que tu negocio necesita ser recordado.</T></h2><p className="mx-auto mt-6 max-w-xl text-base leading-relaxed text-[#c3c3cc]"><T en="Tell us what you are building. The first conversation is a good place to make the path ahead clearer.">Cuéntanos qué estás construyendo. La primera conversación es un buen lugar para hacer más claro el camino.</T></p><button type="button" onClick={() => navigate("/cotizar")} className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#5266eb] px-6 py-3 text-base font-medium text-white transition-colors hover:bg-[#6275ff] active:scale-[0.98] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#5266eb]/35"><T en="Plan your project">Planifica tu proyecto</T><Rocket size={17} aria-hidden="true" /></button></motion.div></section>
  </main><Footer variant="mercury" /></div>;
}
