import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, ArrowUpRight, Check, ChevronDown, Code2, Compass, Globe2, Layers3, Rocket, ShoppingCart, Sparkles } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { T, useLanguage } from "../context/LanguageContext";

const services = [
  { number: "01", title: "Landing Pages", label: { es: "CONVERSIÓN", en: "CONVERSION" }, description: { es: "Páginas claras y veloces para que las personas correctas entiendan el valor y den el siguiente paso.", en: "Clear, fast pages that help the right people understand your value and take the next step." }, points: [{ es: "Captura rápida de leads", en: "Fast lead capture" }, { es: "Diseño móvil optimizado", en: "Mobile-first layout" }, { es: "WhatsApp directo integrado", en: "Direct WhatsApp integration" }], href: "/blog/landing-pages-conversion" },
  { number: "02", title: "E-commerce", label: { es: "VENTAS 24/7", en: "SELL 24/7" }, description: { es: "Plataformas de venta online diseñadas para que el recorrido de compra sea ágil, seguro y fácil de administrar.", en: "Online sales platforms designed to keep the buying journey effortless, secure and easy to manage." }, points: [{ es: "Pasarela segura de pago", en: "Secure payment gateway" }, { es: "Administrador de productos", en: "Product management" }, { es: "Compra ágil", en: "Frictionless checkout" }], href: "/blog/ecommerce-alto-nivel" },
  { number: "03", title: { es: "Webs Corporativas", en: "Corporate Websites" }, label: { es: "AUTORIDAD", en: "AUTHORITY" }, description: { es: "Una identidad digital sólida para empresas que necesitan transmitir confianza, criterio y dirección.", en: "A solid digital identity for companies that need to communicate trust, judgment and direction." }, points: [{ es: "Arquitectura a medida", en: "Custom architecture" }, { es: "Estrategia de contenido", en: "Content strategy" }, { es: "Escalable desde el inicio", en: "Scalable from day one" }], href: "/blog/webs-corporativas-identidad" },
];

const plans = [
  { number: "01", title: { es: "Paquete Destello", en: "Flash Package" }, price: "$299", description: { es: "Una página diseñada para convertir visitantes en clientes desde el primer scroll.", en: "One page designed to turn visitors into clients from the first scroll." }, items: [{ es: "Diseño exclusivo y responsivo", en: "Exclusive responsive design" }, { es: "WhatsApp integrado", en: "WhatsApp integration" }, { es: "SEO On-Page", en: "On-page SEO" }, { es: "Entrega en 1–2 semanas", en: "Delivered in 1–2 weeks" }], warranty: { es: "30 días de garantía post-lanzamiento", en: "30-day post-launch warranty" } },
  { number: "02", title: { es: "Paquete Constelación", en: "Constellation Package" }, price: "$699", description: { es: "Sitio corporativo de hasta 5 páginas con chatbot IA, blog y Analytics.", en: "Corporate site of up to 5 pages with an AI chatbot, blog and Analytics." }, items: [{ es: "Todo lo de Destello", en: "Everything in Flash" }, { es: "Hasta 5 páginas", en: "Up to 5 pages" }, { es: "Chatbot IA 24/7", en: "24/7 AI chatbot" }, { es: "SEO Técnico + Search Console", en: "Technical SEO + Search Console" }], warranty: { es: "60 días de garantía post-lanzamiento", en: "60-day post-launch warranty" }, featured: true },
  { number: "03", title: { es: "Paquete Nova", en: "Nova Package" }, price: "$1,299", description: { es: "Plataforma de ventas completa con pagos, panel administrativo y una herramienta IA.", en: "Complete sales platform with payments, an admin panel and one AI tool." }, items: [{ es: "Todo lo de Constelación", en: "Everything in Constellation" }, { es: "E-commerce + Stripe y PayPal", en: "E-commerce + Stripe and PayPal" }, { es: "Panel admin personalizado", en: "Custom admin panel" }, { es: "Schema Markup", en: "Schema Markup" }], warranty: { es: "90 días de garantía prioritaria", en: "90-day priority warranty" } },
];

const faqs = [
  { es: "¿Cuánto cuesta un proyecto?", en: "How much does a project cost?", answerEs: "Los proyectos profesionales y personalizados comienzan desde $299 USD. La inversión se define con claridad según la complejidad y las necesidades del negocio.", answerEn: "Custom professional projects start at $299 USD. The investment is defined clearly around the business's complexity and needs." },
  { es: "¿Ofrecen facilidades de pago?", en: "Do you offer payment plans?", answerEs: "Sí. Trabajamos con 50% al iniciar el proyecto y 50% al momento del lanzamiento. En proyectos mayores podemos estructurar pagos por fases.", answerEn: "Yes. We work with 50% to start and 50% at launch. For larger projects, we can structure milestone payments." },
  { es: "¿Cuánto tiempo toma un proyecto?", en: "How long does a project take?", answerEs: "Depende de la complejidad. Una landing page suele estar lista en 2 semanas y una web corporativa completa puede tomar entre 4 y 6 semanas.", answerEn: "It depends on complexity. A landing page is usually ready in 2 weeks, while a complete corporate website can take 4 to 6 weeks." },
  { es: "¿Trabajan con SEO y mantenimiento?", en: "Do you provide SEO and maintenance?", answerEs: "Sí. Todas nuestras webs nacen con una estructura SEO On-Page optimizada y contamos con planes de soporte para mantenerlas actualizadas y seguras.", answerEn: "Yes. Every website starts with optimized on-page SEO and we offer support plans to keep it current and secure." },
];

function ParticleOrb() {
  const dots = useMemo(() => Array.from({ length: 170 }, (_, index) => {
    const seed = index * 47.7;
    const theta = seed * 0.618;
    const phi = Math.acos(1 - 2 * ((index + 0.5) / 170));
    const radius = 184;
    const x = 220 + radius * Math.sin(phi) * Math.cos(theta);
    const y = 220 + radius * Math.cos(phi);
    const depth = (Math.sin(phi) * Math.sin(theta) + 1) / 2;
    return { id: index, x, y, r: 1.1 + depth * 2.1, opacity: 0.22 + depth * 0.78, violet: index % 17 === 0 };
  }), []);
  return <div className="relative mx-auto aspect-square w-[min(82vw,590px)]" aria-hidden="true"><div className="absolute inset-[8%] rounded-full bg-[radial-gradient(circle,rgba(14,165,233,.22)_0%,rgba(99,102,241,.12)_44%,transparent_70%)]" /><svg viewBox="0 0 440 440" className="relative h-full w-full overflow-visible"><g className="auros-orb-rotate"><ellipse cx="220" cy="220" rx="194" ry="77" fill="none" stroke="rgba(224,242,254,.16)" strokeWidth="1" /><ellipse cx="220" cy="220" rx="190" ry="88" fill="none" stroke="rgba(99,102,241,.26)" strokeWidth="1" transform="rotate(62 220 220)" /><ellipse cx="220" cy="220" rx="188" ry="74" fill="none" stroke="rgba(14,165,233,.22)" strokeWidth="1" transform="rotate(-45 220 220)" /></g><g className="auros-orb-pulse">{dots.map((dot) => <circle key={dot.id} cx={dot.x} cy={dot.y} r={dot.r} fill={dot.violet ? "#c4b5fd" : "#e0f2fe"} opacity={dot.opacity} />)}</g><circle cx="220" cy="220" r="111" fill="none" stroke="rgba(224,242,254,.12)" strokeWidth="1" /><circle cx="220" cy="220" r="10" fill="#e0f2fe" opacity=".9" /></svg></div>;
}

function ConnectionDiagram() {
  return <svg viewBox="0 0 400 280" className="h-auto w-full max-w-md" aria-hidden="true"><g fill="none" stroke="rgba(203,213,225,.34)" strokeWidth="1"><path d="M45 75L155 140L280 68L354 162L244 232L155 140L80 223" /><path d="M45 75L80 223M280 68L244 232" /></g>{[[45,75],[155,140],[280,68],[354,162],[244,232],[80,223]].map(([cx, cy], index) => <g key={`${cx}-${cy}`}><circle cx={cx} cy={cy} r={index === 1 ? 18 : 10} fill={index === 1 ? "#6366f1" : "#0f172a"} stroke="rgba(224,242,254,.75)" /><circle cx={cx} cy={cy} r={index === 1 ? 5 : 3} fill="#e0f2fe" /></g>)}</svg>;
}

function ProjectFrame() {
  return <figure className="auros-card overflow-hidden"><div className="flex h-11 items-center gap-2 border-b border-white/10 px-4" aria-hidden="true"><span className="h-2 w-2 rounded-full bg-slate-500" /><span className="h-2 w-2 rounded-full bg-slate-500" /><span className="h-2 w-2 rounded-full bg-slate-500" /><span className="ml-4 h-4 max-w-72 flex-1 rounded-sm bg-white/[0.08]" /></div><div className="relative aspect-video overflow-hidden"><img src="/screenshots/la-reja-desktop.svg" alt="Vista de La Reja, proyecto del portafolio de Polaris Web Studio" className="h-full w-full object-cover object-top" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#020617]/90 via-[#020617]/25 to-transparent px-5 pb-5 pt-16"><p className="text-sm text-[#e0f2fe]">La Reja · <T en="Digital restaurant experience">Experiencia gastronómica digital</T></p></div></div></figure>;
}

function Eyebrow({ children }: { children: ReactNode }) { return <p className="text-xs font-medium uppercase tracking-[0.13em] text-[#cbd5e1]">{children}</p>; }

export default function LandingPage() {
  const navigate = useNavigate();
  const { language } = useLanguage();
  const reducedMotion = useReducedMotion();
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  useEffect(() => {
    document.title = language === "es" ? "Polaris Web Studio | Diseño y Desarrollo de Páginas Web Premium" : "Polaris Web Studio | Premium Web Design & Development";
    const meta = document.querySelector('meta[name="description"]') ?? document.head.appendChild(document.createElement("meta"));
    meta.setAttribute("name", "description");
    meta.setAttribute("content", language === "es" ? "Diseñamos y desarrollamos experiencias web originales para atraer clientes y hacer crecer negocios." : "We design and develop original web experiences that attract clients and help businesses grow.");
  }, [language]);

  const reveal = (delay = 0) => ({ initial: { opacity: 0, y: reducedMotion ? 0 : 14 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.16 }, transition: { duration: reducedMotion ? 0 : 0.42, delay, ease: [0.16, 1, 0.3, 1] as [number, number, number, number] } });

  return <div className="auros-page min-h-screen overflow-x-clip bg-[#020617] text-[#f8fafc]"><Navbar variant="auros" /><main>
    <section className="relative isolate flex min-h-[100svh] items-center overflow-hidden bg-[#020617] px-6 pb-20 pt-28 md:px-12 lg:px-16"><div className="pointer-events-none absolute inset-0 -z-20 bg-[radial-gradient(circle_at_73%_46%,rgba(14,165,233,.16),transparent_23%),radial-gradient(circle_at_71%_50%,rgba(99,102,241,.18),transparent_43%),linear-gradient(180deg,#020617_0%,#081329_100%)]" aria-hidden="true" /><div className="pointer-events-none absolute right-[-7%] top-[13%] -z-10 opacity-90 lg:right-[4%] lg:top-[12%]" aria-hidden="true"><ParticleOrb /></div><div className="relative mx-auto grid w-full max-w-[1440px] items-center gap-10 lg:grid-cols-[0.82fr_1.18fr]"><motion.div initial={{ opacity: 0, y: reducedMotion ? 0 : 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reducedMotion ? 0 : 0.52, ease: [0.16, 1, 0.3, 1] as [number, number, number, number] }} className="max-w-2xl"><Eyebrow><T en="POLARIS WEB STUDIO · DIGITAL ENGINEERING">POLARIS WEB STUDIO · INGENIERÍA DIGITAL</T></Eyebrow><h1 className="auros-display mt-7 max-w-3xl text-[3.35rem] leading-[0.95] text-white sm:text-7xl lg:text-[5.65rem]"><T en="A clearer signal for what your business can become.">Una señal más clara de lo que tu negocio puede llegar a ser.</T></h1><p className="mt-7 max-w-xl text-base leading-relaxed text-[#cbd5e1] sm:text-lg"><T en="We turn strategy, design and technology into digital experiences that help the right people understand, trust and choose your business.">Convertimos estrategia, diseño y tecnología en experiencias digitales que ayudan a las personas correctas a entender, confiar y elegir tu negocio.</T></p><div className="mt-9 flex flex-col items-start gap-4 sm:flex-row sm:items-center"><button type="button" onClick={() => navigate("/cotizar")} className="auros-gradient-action inline-flex min-h-12 items-center gap-2 rounded-md px-[22px] py-3 text-sm font-bold uppercase tracking-[0.04em] text-[#020617] transition-transform hover:brightness-105 active:scale-[0.98] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#c4b5fd]/40"><T en="Plan your project">Planifica tu proyecto</T><ArrowRight size={17} aria-hidden="true" /></button><a href="#explorar" className="inline-flex min-h-12 items-center gap-2 rounded-md px-4 py-3 text-sm text-[#e0f2fe] transition-colors hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#c4b5fd]"><T en="Explore Polaris">Explora Polaris</T><ArrowUpRight size={16} aria-hidden="true" /></a></div></motion.div><div className="hidden lg:block" aria-hidden="true" /></div><div className="absolute bottom-7 left-6 right-6 flex justify-between text-xs text-[#94a3b8] md:left-12 md:right-12 lg:left-16 lg:right-16"><span><T en="SYSTEM // 01">SISTEMA // 01</T></span><span><T en="Strategy · Design · Technology">Estrategia · Diseño · Tecnología</T></span></div></section>

    <section id="explorar" className="bg-[#020617] px-6 py-[80px] md:px-12 lg:px-16"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[1.15fr_0.85fr] lg:items-end"><motion.div {...reveal()}><Eyebrow><T en="EXPLORE">EXPLORA</T></Eyebrow><h2 className="auros-display mt-5 max-w-3xl text-4xl leading-none text-white sm:text-5xl"><T en="A digital system built around the next right move.">Un sistema digital construido alrededor del siguiente paso correcto.</T></h2><p className="mt-6 max-w-2xl text-base leading-relaxed text-[#cbd5e1]"><T en="A compelling site is not an isolated asset. It creates a clear path from first impression to meaningful action.">Un sitio que convence no es un activo aislado. Crea un camino claro desde la primera impresión hasta una acción significativa.</T></p></motion.div><motion.div {...reveal(0.08)} className="hidden justify-self-end lg:block"><ConnectionDiagram /></motion.div></div><div className="mx-auto mt-12 grid max-w-[1440px] gap-3 md:grid-cols-3">{services.map((service, index) => { const titleEs = typeof service.title === "string" ? service.title : service.title.es; const titleEn = typeof service.title === "string" ? service.title : service.title.en; return <motion.article {...reveal(index * 0.06)} key={service.number} className="auros-card flex min-h-[365px] flex-col p-9"><div className="flex items-start justify-between"><span className="text-[5rem] leading-none tracking-[-0.06em] text-[#ddd6fe]">{service.number}</span><Link to={service.href} className="flex h-8 w-8 items-center justify-center rounded-md bg-[#1e293b] text-white transition-colors hover:bg-[#334155] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#c4b5fd]" aria-label={`${titleEs} — ${language === "es" ? "ver más" : "read more"}`}><ArrowUpRight size={16} aria-hidden="true" /></Link></div><Eyebrow><T en={service.label.en}>{service.label.es}</T></Eyebrow><h3 className="auros-display mt-3 text-3xl leading-none text-white"><T en={titleEn}>{titleEs}</T></h3><p className="mt-4 text-sm leading-relaxed text-[#cbd5e1]"><T en={service.description.en}>{service.description.es}</T></p><ul className="mt-auto space-y-2.5 pt-7">{service.points.map((point) => <li key={point.es} className="flex gap-2 text-sm text-[#cbd5e1]"><Check size={15} className="mt-0.5 shrink-0 text-[#e0f2fe]" aria-hidden="true" /><T en={point.en}>{point.es}</T></li>)}</ul></motion.article>; })}</div></section>

    <section id="portafolio" className="bg-[#0b1024] px-6 py-[80px] md:px-12 lg:px-16"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[0.78fr_1.22fr] lg:items-center"><motion.div {...reveal()}><Eyebrow><T en="SELECTED WORK">PROYECTOS SELECCIONADOS</T></Eyebrow><h2 className="auros-display mt-5 max-w-md text-4xl leading-none text-white sm:text-5xl"><T en="Work with a point of view, not a template.">Trabajo con punto de vista, no con plantilla.</T></h2><p className="mt-6 max-w-md text-base leading-relaxed text-[#cbd5e1]"><T en="Every project starts with a different audience, business model and objective. The outcome should reflect that reality.">Cada proyecto comienza con un público, modelo de negocio y objetivo distintos. El resultado debe reflejar esa realidad.</T></p><Link to="/portafolio" className="mt-8 inline-flex min-h-11 items-center gap-2 rounded-md border border-[#cbd5e1]/45 px-5 py-2 text-sm text-[#e0f2fe] transition-colors hover:border-white hover:text-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#c4b5fd]/30"><T en="See the portfolio">Ver el portafolio</T><ArrowRight size={16} aria-hidden="true" /></Link></motion.div><motion.div {...reveal(0.08)}><ProjectFrame /></motion.div></div></section>

    <section id="proceso" className="bg-[#020617] px-6 py-[80px] md:px-12 lg:px-16"><div className="mx-auto max-w-[1440px]"><motion.header {...reveal()} className="max-w-2xl"><Eyebrow><T en="A WAY OF WORKING">UNA FORMA DE TRABAJAR</T></Eyebrow><h2 className="auros-display mt-5 text-4xl leading-none text-white sm:text-5xl"><T en="The process makes room for the work that matters.">El proceso deja espacio para el trabajo que importa.</T></h2></motion.header><div className="mt-12 grid gap-3 md:grid-cols-3">{[{ n: "01", es: "Planificamos", en: "We plan", copyEs: "Alineamos objetivos, público, alcance y las decisiones que realmente importan.", copyEn: "We align goals, audience, scope and the decisions that really matter." }, { n: "02", es: "Diseñamos", en: "We design", copyEs: "Convertimos la estrategia en una experiencia clara, distintiva y preparada para convertir.", copyEn: "We turn strategy into a clear, distinctive experience ready to convert." }, { n: "03", es: "Lanzamos", en: "We launch", copyEs: "Publicamos sobre una base técnica sólida y acompañamos los primeros pasos.", copyEn: "We launch on a solid technical foundation and support the first steps." }].map((step, index) => <motion.article {...reveal(index * 0.06)} key={step.n} className="auros-card p-9"><span className="text-[4rem] leading-none tracking-[-0.06em] text-[#ddd6fe]">{step.n}</span><h3 className="auros-display mt-8 text-3xl leading-none text-white"><T en={step.en}>{step.es}</T></h3><p className="mt-4 text-sm leading-relaxed text-[#cbd5e1]"><T en={step.copyEn}>{step.copyEs}</T></p></motion.article>)}</div><Link to="/proceso" className="mt-8 inline-flex items-center gap-2 text-sm text-[#e0f2fe] hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#c4b5fd]"><T en="Explore the process">Conoce la metodología</T><ArrowRight size={16} aria-hidden="true" /></Link></div></section>

    <section id="precios" className="bg-[#020617] px-6 py-[80px] md:px-12 lg:px-16"><div className="mx-auto max-w-[1440px]"><motion.header {...reveal()} className="max-w-2xl"><Eyebrow><T en="TRANSPARENT PRICING">INVERSIÓN TRANSPARENTE</T></Eyebrow><h2 className="auros-display mt-5 text-4xl leading-none text-white sm:text-5xl"><T en="A clear starting point for every stage.">Un punto de partida claro para cada etapa.</T></h2><p className="mt-5 text-base leading-relaxed text-[#cbd5e1]"><T en="Fixed prices, no hidden costs. Start with the scope that makes sense today.">Precios fijos, sin costos ocultos. Empieza con el alcance que tiene sentido hoy.</T></p></motion.header><div className="mt-12 grid gap-3 md:grid-cols-3">{plans.map((plan, index) => <motion.article {...reveal(index * 0.06)} key={plan.number} className="auros-card relative flex min-h-[455px] flex-col p-9">{plan.featured && <span className="absolute right-6 top-6 rounded-md bg-[#1e293b] px-3 py-1 text-xs text-[#e0f2fe]"><T en="Most popular">Más popular</T></span>}<span className="text-[4rem] leading-none tracking-[-0.06em] text-[#ddd6fe]">{plan.number}</span><h3 className="auros-display mt-8 text-3xl leading-none text-white"><T en={plan.title.en}>{plan.title.es}</T></h3><p className="auros-display mt-6 text-5xl leading-none text-[#ddd6fe]">{plan.price}</p><p className="mt-5 text-sm leading-relaxed text-[#cbd5e1]"><T en={plan.description.en}>{plan.description.es}</T></p><ul className="mt-6 space-y-2.5">{plan.items.map((item) => <li key={item.es} className="flex gap-2 text-sm text-[#cbd5e1]"><Check size={15} className="mt-0.5 shrink-0 text-[#e0f2fe]" aria-hidden="true" /><T en={item.en}>{item.es}</T></li>)}</ul><p className="mt-auto pt-7 text-xs text-[#94a3b8]"><T en={plan.warranty.en}>{plan.warranty.es}</T></p><button type="button" onClick={() => navigate("/cotizar")} className="mt-5 inline-flex min-h-11 items-center justify-center rounded-md bg-[#1e293b] px-5 py-2 text-sm text-[#e0f2fe] transition-colors hover:bg-[#334155] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#c4b5fd]/30"><T en="Start here">Comenzar</T></button></motion.article>)}</div><p className="mt-7 text-xs text-[#94a3b8]"><T en="All packages include a domain up to $15 USD (first year), SSL and managed hosting.">Todos los paquetes incluyen dominio web hasta $15 USD (primer año), SSL y hosting administrado.</T></p></div></section>

    <section id="soluciones" className="bg-[#0b1024] px-6 py-[80px] md:px-12 lg:px-16"><div className="mx-auto max-w-[1440px]"><motion.header {...reveal()} className="max-w-2xl"><Eyebrow><T en="THE POLARIS ECOSYSTEM">EL ECOSISTEMA POLARIS</T></Eyebrow><h2 className="auros-display mt-5 text-4xl leading-none text-white sm:text-5xl"><T en="More ways to move a business forward.">Más formas de impulsar un negocio.</T></h2></motion.header><div className="mt-12 grid gap-3 md:grid-cols-3">{[{ label: { es: "NÚCLEO DIGITAL", en: "DIGITAL CORE" }, title: { es: "Diseño y desarrollo web", en: "Web design and development" }, text: { es: "Landing pages, webs corporativas y e-commerce construidos alrededor de objetivos reales.", en: "Landing pages, corporate websites and e-commerce built around real goals." }, link: "/cotizar", action: { es: "Cotiza tu proyecto", en: "Quote your project" }, icon: Code2 }, { label: { es: "PRESENCIA LOCAL", en: "LOCAL PRESENCE" }, title: { es: "Local Lift", en: "Local Lift" }, text: { es: "Una forma enfocada de mejorar cómo aparece, comunica y se descubre un negocio a nivel local.", en: "A focused way to improve how a business appears, communicates and gets discovered locally." }, link: "/local-lift", action: { es: "Conoce Local Lift", en: "Explore Local Lift" }, icon: Compass }, { label: { es: "OPERACIONES", en: "OPERATIONS" }, title: { es: "Polaris Flow", en: "Polaris Flow" }, text: { es: "Sistemas enfocados para ordenar las partes repetitivas del negocio y avanzar con más claridad.", en: "Focused systems that organize a business's repetitive parts and help the team move with more clarity." }, link: "/flow", action: { es: "Explora Polaris Flow", en: "Explore Polaris Flow" }, icon: Sparkles }].map((solution, index) => { const Icon = solution.icon; return <motion.article {...reveal(index * 0.06)} key={solution.title.en} className="auros-card flex min-h-[295px] flex-col p-9"><Icon size={20} className="text-[#e0f2fe]" aria-hidden="true" /><Eyebrow><span className="mt-9 block"><T en={solution.label.en}>{solution.label.es}</T></span></Eyebrow><h3 className="auros-display mt-3 text-3xl leading-none text-white"><T en={solution.title.en}>{solution.title.es}</T></h3><p className="mt-4 text-sm leading-relaxed text-[#cbd5e1]"><T en={solution.text.en}>{solution.text.es}</T></p><Link to={solution.link} className="mt-auto pt-7 inline-flex items-center gap-2 text-sm text-[#e0f2fe] hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#c4b5fd]"><T en={solution.action.en}>{solution.action.es}</T><ArrowRight size={15} aria-hidden="true" /></Link></motion.article>; })}</div></div></section>

    <section id="faq" className="bg-[#020617] px-6 py-[80px] md:px-12 lg:px-16"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[0.78fr_1.22fr]"><motion.header {...reveal()}><Eyebrow><T en="COMMON QUESTIONS">DUDAS COMUNES</T></Eyebrow><h2 className="auros-display mt-5 max-w-md text-4xl leading-none text-white sm:text-5xl"><T en="The details should be as clear as the idea.">Los detalles deben ser tan claros como la idea.</T></h2><Link to="/contacto" className="mt-8 inline-flex items-center gap-2 text-sm text-[#e0f2fe] hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#c4b5fd]"><T en="Contact Polaris">Contactar a Polaris</T><ArrowRight size={15} aria-hidden="true" /></Link></motion.header><div className="auros-card overflow-hidden">{faqs.map((faq, index) => { const open = openFaq === index; return <motion.article {...reveal(index * 0.04)} key={faq.es} className="border-b border-white/10 last:border-b-0"><button type="button" onClick={() => setOpenFaq(open ? null : index)} aria-expanded={open} className="flex w-full items-center justify-between gap-6 px-6 py-6 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#c4b5fd] sm:px-8"><span className="auros-display text-xl leading-[1.15] text-white sm:text-2xl"><T en={faq.en}>{faq.es}</T></span><ChevronDown size={20} className={`shrink-0 text-[#e0f2fe] transition-transform ${open ? "rotate-180" : ""}`} aria-hidden="true" /></button>{open && <p className="max-w-2xl px-6 pb-6 text-sm leading-relaxed text-[#cbd5e1] sm:px-8"><T en={faq.answerEn}>{faq.answerEs}</T></p>}</motion.article>; })}</div></div></section>

    <section className="bg-[#020617] px-6 py-[100px] md:px-12 lg:px-16"><motion.div {...reveal()} className="mx-auto max-w-[1440px] rounded-2xl bg-[#0b1024] px-7 py-20 text-center sm:px-12"><Eyebrow><T en="READY WHEN YOU ARE">CUANDO ESTÉS LISTO</T></Eyebrow><h2 className="auros-display mx-auto mt-6 max-w-3xl text-4xl leading-none text-white sm:text-5xl"><T en="Build the next thing your business needs to be seen for.">Construyamos eso por lo que tu negocio necesita ser recordado.</T></h2><p className="mx-auto mt-6 max-w-xl text-base leading-relaxed text-[#cbd5e1]"><T en="Tell us what you are building. The first conversation is a good place to make the path ahead clearer.">Cuéntanos qué estás construyendo. La primera conversación es un buen lugar para hacer más claro el camino.</T></p><button type="button" onClick={() => navigate("/cotizar")} className="auros-gradient-action mt-9 inline-flex min-h-12 items-center gap-2 rounded-md px-[22px] py-3 text-sm font-bold uppercase tracking-[0.04em] text-[#020617] transition-transform hover:brightness-105 active:scale-[0.98] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#c4b5fd]/40"><T en="Plan your project">Planifica tu proyecto</T><Rocket size={17} aria-hidden="true" /></button></motion.div></section>
  </main><Footer variant="auros" /></div>;
}
